name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: /home/runner/work/not-as-easy-villagers/not-as-easy-villagers/build/libs/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
